sudo: required
services:
  - docker

before_install:
  - docker build -t checkmatez/docker-frontend -f Dockerfile.dev .

script:
  - docker run checkmatez/docker-frontend yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-201041147851'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
